config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do

    member do 
      post 'vote'
    end
  	
    resources :comments, only: [:create] do
      member do 
        post 'vote'
      end
    end
  end

  resources :categories, except: [:destroy]
  resources :users, only: [:create, :edit, :show, :index, :update]

  
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true

  after_validation :generate_slug

  def generate_slug
    self.slug = self.name.gsub(' ', '-').downcase
  end

  def to_param
    self.slug
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  belongs_to :post

  has_many :votes, as: :voteable

  validates :body, presence: true

  
  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
  	self.votes.where(vote: true).size
  end

  def down_votes
  	self.votes.where(vote: false).size
  end
end

app/models/post.rb
class Post < ActiveRecord::Base


  belongs_to :creator, foreign_key: :user_id, class_name: 'User'
  has_many :comments

  has_many :post_categories
  has_many :categories, through: :post_categories

  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true

  accepts_nested_attributes_for :categories, :post_categories

  after_validation :generate_slug

  def total_votes
    self.up_votes - self.down_votes
  end

  def up_votes
  	self.votes.where(vote: true).size
  end

  def down_votes
  	self.votes.where(vote: false).size
  end

  def generate_slug
    self.slug = self.title.gsub(' ', '-').downcase
  end

  def to_param
    self.slug
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base


  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, foreign_key: :user_id
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}

  after_validation :generate_slug

  def admin?
  	self.role == 'admin'
  end

  def moderator?
  	self.role == 'moderator'
  end

  def admin_or_current_user
    self.logged_in? || current_user.admin?  
  end

  def generate_slug
    self.slug = self.username.gsub(' ', '-').downcase
  end

  def to_param
    self.slug
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user, :logged_in?, :not_yet_voted, :logged_in_or_admin?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that"
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? && current_user.admin?   
  end

  def access_denied
    flash[:error] = "You can't do that"
    redirect_to root_path
  end

  def not_yet_voted(voteable_object)
    true unless voteable_object.votes.where(user_id: current_user.id).size != 0
  end

  def admin
    !!current_user.admin?
  end

  def logged_in_or_admin?
    !!logged_in? || !!admin?
  end




end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  before_action :set_category, only: [:show, :edit, :update] 
  before_action :require_user, except: [:index, :show]
  before_action :require_admin, only: [:create]

  def index
    @categories = Category.all
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(post_params)

    if @category.save
      flash[:notice] = "Your category was saved."
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @category.update(post_params)
      flash[:notice] = "Your category was edited."
      redirect_to category_path(@category)
    else
      render :edit
    end
  end


  def show
  end

  def post_params
    params.require(:category).permit(:name)
  end

  private

  def set_category
    @category = Category.find_by(slug: params[:id])  
  end  


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :require_user

  def create
  	@post = Post.find_by(slug: params[:post_id])
  	@comment = @post.comments.new(comment_params)
  	@comment.creator = current_user
  	if @comment.save
  		flash[:notice] = "Your comment was created"
  		redirect_to post_path(@post)
  	else
  		render 'posts/show'
  	end
  end

  def comment_params
  	params.require(:comment).permit(:body)
  end

  def vote
    post = Post.find_by(slug: params[:post_id])  
    @comment = Comment.find(params[:id])
    Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
      respond_to do |format|
        format.html { redirect_to :back, notice: "Your vote was counted" }
        format.js   {}
      end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:show, :edit, :update, :vote] 
before_action :require_user, except: [:index, :show, :vote]
before_action :logged_in_or_admin?, only: [:edit]

  def index
    @posts = Post.all.sort_by {|x| x.total_votes}.reverse
  end

  def new
  	@post = Post.new
    @categories = Category.all
  end

  def create
  	@post = Post.new(post_params)
    @post.creator = current_user
 
    if @post.save
      flash[:notice] = "Your post was saved."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update

    if @post.update(post_params)
      flash[:notice] = "Your post was edited."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  
  def show
    @comment = Comment.new
  end

  def vote
    Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html { redirect_to :back, notice: "Your vote was counted" }
      format.js   {}
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])  
  end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've logged in!"
      redirect_to root_path
    else
      flash[:error] = "There something wrong with your username or password"
      redirect_to register_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update] 
  before_action :require_admin, only: [:index]
  before_action :logged_in_or_admin?, only: [:edit, :update]
  
 
  def new
    @user = User.new
   end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You are registered"
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User has been was updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
  end

  
  private

  def user_params
    params.require(:user).permit(:username, :password, :phone, :time_zone)
  end

  def set_user
    @user = User.find_by(slug: params[:id])  
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper

	def fix_url(str)
		str.starts_with?("http://") ? str : "http://#{str}"
  end

  def display_datetime(dt)
  	if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
  	end
  	dt.strftime("%m/%d/%Y 1:%M%P %Z")
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<br />

	<%= f.submit "Create category", class: 'btn btn-primary' %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'categories/form' %>

app/views/categories/index.html.erb
<h3>All Categories</h3>

<% if current_user.admin? %>
  <p><%= link_to "Create category", new_category_path %></p>
<% end %>

<% @categories.each do |cat| %>
  <p><%= link_to cat.name, category_path(cat) %>
  	 <% if logged_in? %> 
  	   [<%= link_to 'edit category', edit_category_path(cat) %>]
  	   <% end %>
  </p>
  <br />
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'categories/form' %>

app/views/categories/show.html.erb
<h4><%= @category.name %></h4>


<%= link_to 'Edit Category', edit_category_path(@category) %>
<br />
<br />
Post(s):
<br />
<br />
<ul>
  <% @category.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

app/views/comments/vote.js.erb
$('#comment_<%= @comment.id %>_votes').html('<%= @comment.total_votes %>');

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'Posts', posts_path %>
  </li>
   <li>
    <%= link_to 'Categories', categories_path %>

    <% if logged_in? && current_user.admin? %>
    <li>
    <%= link_to 'Users', users_path %>
    </li>
    <% end %>
  </li>

  <% if logged_in? %>
   <li>
    <%= link_to current_user.username, user_path(current_user) %>
   </li>
   <li>
    <%= link_to 'logout', logout_path %>
   </li>
  <% else %>
  <li>
    <%= link_to 'Register', register_path %>
  </li>
  <li>
    <%= link_to 'Login', login_path %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.label :url %>
	<%= f.text_field :url %>
	<br />
	<%= f.label :description %>
	<%= f.text_area :description %>
	<br />
  <%= f.label "Categories" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
    <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  <% end %>
  <br />
  <br />
	<%= f.submit "Create post", class: 'btn btn-primary' %>
	<br />
<% end %>

app/views/posts/_post.html.erb
<div class="row">
	<div class="span0 well text-center">
		<% if logged_in? && not_yet_voted(post) %>

		  <%= link_to vote_post_path(post, vote: 'true'), method: 'post', remote: true do %>
		    <i class="icon-arrow-up"></i>
		  <% end %>
	
		  <br />
		<% end %>
		<span id='<%="post_#{post.id}_votes" %>'><%= post.total_votes %></span> votes
		<br />

		<% if logged_in? && not_yet_voted(post) %>

		   <%= link_to vote_post_path(post, vote: 'false'), remote: true, method: 'post' do %>
		    <i class="icon-arrow-down"></i></i>
		  <% end %>
	
		<% end %>

	</div>

	<div class='span8 well'>
		<h4><%= link_to post.title, fix_url(post.url) %></h4>
		<p>
			<%= post.description %>
		</p>
		<p>
			<span class="quiet">posted by</span> <%= link_to post.creator.username, '' %>
			<small> at <%= display_datetime(post.created_at) %></small>
		</p>
		<small>
			<span>
				<%= link_to("#{post.comments.size} comments", post_path(post)) %>
			</span>
		</small>
	
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h3>All Posts</h3>

<% if logged_in? %>
  <p><%= link_to "Create new post", new_post_path %></p>
<% end %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
  <br /><br />
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, url: {action: "create"} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.label :url %>
	<%= f.text_field :url %>
	<br />
	<%= f.submit "Create post" %>
<% end %>

app/views/posts/show.html.erb
<h4>Showing Post</h4>
<br />
Title: <%= link_to @post.title, fix_url(@post.url) %>
</br>
URL: <%= @post.url %>
<br />
Description: <%= @post.description %>
<br />
<% if logged_in? %>
  <%= link_to 'Edit Post', edit_post_path(@post) %>
  <br />
<% end %>
Categories: <% @post.categories.each do |cat| %>
              <%= cat.name %>
            <% end %>


<h5>Comments:</h5>

<% if logged_in? %>
<%= render 'shared/errors', obj: @comment %>
<%= form_for [@post, @comment] do |f| %>
	<%= f.text_area :body %>
	<br />
	<%= f.submit "Create Comment" %>
<% end %>
<% end %>


<% @post.reload.comments.each do |comment| %>
<div class="row">
<div class="span0 well text-center">
		<% if logged_in? && not_yet_voted(comment) %>

		  <%= link_to vote_post_comment_path(@post, comment, vote: 'true'), remote: true, method: 'post' do %>
		    <i class="icon-arrow-up"></i>
		  <% end %>

		  <br />
		<% end %>
		<span id='<%="comment_#{comment.id}_votes" %>'><%= comment.total_votes %></span> votes
		<br />

		<% if logged_in? && not_yet_voted(comment) %>
		   <%= link_to vote_post_comment_path(@post, comment, vote: 'false'), remote: true, method: 'post' do %>
		    <i class="icon-arrow-down"></i></i>
		  <% end %>
		<% end %>

	</div>
		<div class="span8 well">
 <%= comment.body %>
</div>

</div>
	<% end %>

app/views/posts/vote.js.erb
$('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %>');

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
  	<div class="alert alert-error span8">
  		<h5>Please fix the following errors:</h5>
      <ul>
  	  <% obj.errors.full_messages.each do |msg| %>
  	    <li><%= msg %></li>
  	  <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="well">
	<%= form_for @user do |f| %>
	<%= render 'shared/errors', obj: @user %>
	<div class='control-group'>
	  <%= f.label :username %>
	  <%= f.text_field :username %>
  </div>
  <div class='control-group'>
	  <%= f.label :password %>
	  <%= f.password_field :password %>
  </div>
   <div class='control-group'>
	  <%= f.label :time_zone %>
	  <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %>
	<%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-success' %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h4>Edit Your Profile</h4>
<%= render 'users/form' %>

app/views/users/index.html.erb
<h4>All Users</h4>

<br />
<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.username, user_path(user) %> 
  	<% if logged_in_or_admin? %>
      <%= link_to '(edit user)', edit_user_path(user) %></li>
    <% end %>
  <% end %>
</ul>

app/views/users/new.html.erb
<h4>Register a New User</h4>
<%= render 'users/form' %>

app/views/users/show.html.erb
<h4><%= @user.username %></h4>

<% if logged_in_or_admin? %>
  <p><%= link_to 'Edit User', edit_user_path(@user) %></p>
<% end %>

<p>All posts by <%= @user.username %> </p>
<ul>
	<% @user.posts.all.each do |post| %>
	<li>
		<%= post.title %>
	</li>
	<% end %>
</ul>